language: rust

sudo: required

services: memcache

env:
    - RUST_BACKTRACE=full RUST_TEST_THREADS=1

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev

before_cache:
    - cargo sweep --file

before_script:
    - cargo install cargo-sweep --force
    - cargo sweep --stamp
    - memcached -p 11211 -d

script:
    - cargo test --verbose
    - cargo test --doc
